import json
import os
from datetime import datetime, timezone
from .paths import reports_dir_path
from .utils_redact import redact

def generate_markdown_report(tenant_name, status, check_results, log_findings, reasons, telemetry):
    """Generates the premium Markdown report."""
    emoji = (
        "🔴 FAIL"
        if status == "FAIL"
        else ("🟠 DEPENDENCY_ERROR" if status == "DEPENDENCY_ERROR" else ("🟡 WARN" if status == "WARN" else "✅ OK"))
    )
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    report = f"""# 🛠 Maintenance Report: {tenant_name}
> **Status:** {emoji}
> **Timestamp:** {ts}
> **Run Duration:** {telemetry.get('last_run_duration_ms', 0)}ms
> **Run ID:** {telemetry.get('run_id', 'n/a')}
> **Schema Version:** {telemetry.get('schema_version', 'n/a')}
> **Code Version:** {telemetry.get('code_version', 'n/a')}

## 📊 Service Summary
| Service | Status | Detail |
| :--- | :---: | :--- |
"""
    
    for res in check_results:
        s = "✅ OK" if res.get("ok") else "❌ FAIL"
        detail = f"{res.get('latency_ms', 'N/A')}ms" if res.get('ok') else redact(str(res.get('error', 'Err')))
        name = res.get("type", "Unknown").replace("_", " ").title()
        report += f"| **{name}** | {s} | {detail} |\n"

    if log_findings:
        report += "\n## 🔍 Log Anomalies\n"
        for f in log_findings:
            report += f"- **{f['rule_name']}**: {f['count']} occurrences ({f['severity']})\n"
            if f.get('evidence'):
                report += "  - *Evidence:* `" + redact(", ".join(f['evidence'])) + "`\n"

    actions = telemetry.get("actions") or []
    if actions:
        report += "\n## 🧯 Remediation Actions\n"
        for action in actions:
            report += f"- {action.get('action_type')}: {action.get('status')} ({redact(str(action.get('reason', '')))} )\n"

    if reasons:
        report += "\n## 🚀 Findings & Actions\n"
        for r in reasons:
            report += f"- {redact(r)}\n"
            
    report += "\n---\n*Generated by Maintenance Bot v1.0*"
    return report

def save_reports(tenant_name, status, check_results, log_findings, reasons, telemetry):
    """Saves report in both Markdown and JSON formats."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_dir = os.path.join(reports_dir_path(), today)
    os.makedirs(report_dir, exist_ok=True)
    
    timestamp = datetime.now(timezone.utc).strftime("%H%M")
    base_name = f"{timestamp}_report"
    
    # JSON Data
    full_data = {
        "tenant": tenant_name,
        "status": status,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "run_id": telemetry.get("run_id"),
        "schema_version": telemetry.get("schema_version"),
        "code_version": telemetry.get("code_version"),
        "checks": check_results,
        "log_findings": log_findings,
        "reasons": reasons,
        "telemetry": telemetry
    }
    
    # Save JSON
    with open(os.path.join(report_dir, f"{base_name}.json"), "w") as f:
        json.dump(full_data, f, indent=2)
        
    # Generate & Save Markdown
    md_content = generate_markdown_report(tenant_name, status, check_results, log_findings, reasons, telemetry)
    with open(os.path.join(report_dir, f"{base_name}.md"), "w") as f:
        f.write(md_content)
        
    return md_content, full_data
