"""Default ferreteria knowledge used as fallback when editable files are missing."""

from __future__ import annotations

DEFAULT_SYNONYM_ENTRIES = [
    # --- Fijaciones ---
    {
        "canonical": "tornillo",
        "family": "tornillo",
        "aliases": ["tornillo", "tornillos", "tirafondo", "tirafondos", "bulón", "perno", "bulones"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["chapa", "madera", "durlock"],
    },
    {
        "canonical": "tornillo para chapa",
        "family": "tornillo",
        "aliases": ["tornillo chapa", "para chapa", "chapa"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"use": "chapa", "surface": "chapa", "type": "autoperforante"},
        "context_terms": [],
    },
    {
        "canonical": "tornillo autoperforante",
        "family": "tornillo",
        "aliases": ["tornillo autoperforante", "autoperforante"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"type": "autoperforante"},
        "context_terms": ["chapa"],
    },
    {
        "canonical": "tarugo",
        "family": "tarugo",
        "aliases": ["tarugo", "tarugos", "taco", "tacos", "taco nylon", "taco metalico", "taco de pared", "plug", "rawlplug"],
        "misspellings": ["taco metal"],
        "brand_generic": False,
        "maps_dimensions": {"material": "nylon"},
        "context_terms": ["pared", "piso"],
    },
    {
        "canonical": "taco fisher",
        "family": "tarugo",
        "aliases": ["taco fisher", "tarugo fisher", "fisher"],
        "misspellings": ["fischer"],
        "brand_generic": True,
        "maps_dimensions": {},
        "context_terms": ["nylon"],
    },
    # --- Herramientas Electricas ---
    {
        "canonical": "mecha",
        "family": "mecha",
        "aliases": ["mecha", "mechas", "broca", "brocas", "barrena", "barrenas", "mecha de taladro"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["taladro", "madera", "metal"],
    },
    {
        "canonical": "mecha para madera",
        "family": "mecha",
        "aliases": ["mecha madera", "mecha para madera"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"material": "madera", "surface": "madera"},
        "context_terms": [],
    },
    {
        "canonical": "mecha para metal",
        "family": "mecha",
        "aliases": ["mecha metal", "broca metal", "para metal"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"material": "metal", "surface": "metal"},
        "context_terms": [],
    },
    {
        "canonical": "broca para hormigon",
        "family": "mecha",
        "aliases": ["broca widia", "broca hormigon", "widia"],
        "misspellings": [],
        "brand_generic": True,
        "maps_dimensions": {"material": "hormigon", "surface": "hormigon"},
        "context_terms": [],
    },
    {
        "canonical": "taladro",
        "family": "taladro",
        "aliases": ["taladro", "taladros", "percutor", "rotomartillo", "rotomartillos", "taladro de mano"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["electrico", "bateria"],
    },
    {
        "canonical": "disco",
        "family": "disco",
        "aliases": ["disco", "discos", "disco de corte", "disco flap", "disco diamantado", "rueda de corte"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["amoladora", "corte", "desbaste"],
    },
    {
        "canonical": "sierra",
        "family": "sierra",
        "aliases": ["sierra", "sierras", "serrucho", "serruchos", "hoja de sierra", "hoja sierra"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["madera", "metal"],
    },
    # --- Herramientas Manuales ---
    {
        "canonical": "llave",
        "family": "llave",
        "aliases": ["llave", "llaves", "llave inglesa", "llave fija", "combinada", "llave de tubo"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"type": "ajustable"},
        "context_terms": ["tubo", "fija", "ajustable"],
    },
    {
        "canonical": "llave ajustable",
        "family": "llave",
        "aliases": ["llave ajustable", "francesa", "llave francesa"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"type": "ajustable"},
        "context_terms": [],
    },
    {
        "canonical": "pinza",
        "family": "pinza",
        "aliases": ["pinza", "pinzas", "alicate", "alicates", "tenaza", "tenazas", "morsa de mano"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["electricista", "corte", "presión"],
    },
    {
        "canonical": "martillo",
        "family": "martillo",
        "aliases": ["martillo", "martillos", "mazo", "mazos", "maceta", "maza"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["clavo", "golpe"],
    },
    {
        "canonical": "destornillador",
        "family": "destornillador",
        "aliases": ["destornillador", "destornilladores", "atornillador", "cacciavite", "philips", "plano"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["tornillo", "estrella", "plano"],
    },
    {
        "canonical": "cinta metrica",
        "family": "cinta",
        "aliases": ["cinta", "cinta métrica", "metro", "huincha", "flexómetro", "distanciómetro"],
        "misspellings": ["cinta metrica"],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["medida", "largo"],
    },
    {
        "canonical": "lima",
        "family": "lima",
        "aliases": ["lima", "limas", "escofina", "escofinas"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["metal", "madera", "desbaste"],
    },
    {
        "canonical": "morsa",
        "family": "morsa",
        "aliases": ["morsa", "morsas", "prensa", "prensas", "tornillo de banco", "sargento"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["banco", "sujecion"],
    },
    # --- Pinturas ---
    {
        "canonical": "pintura",
        "family": "pintura",
        "aliases": ["pintura", "esmalte", "barniz", "pintura pared"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["interior", "exterior", "pared"],
    },
    {
        "canonical": "latex",
        "family": "pintura",
        "aliases": ["latex", "pintura latex"],
        "misspellings": ["látex"],
        "brand_generic": False,
        "maps_dimensions": {"type": "latex"},
        "context_terms": [],
    },
    {
        "canonical": "pintura blanca",
        "family": "pintura",
        "aliases": ["pintura blanca", "latex blanco"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"type": "latex", "color": "blanco"},
        "context_terms": [],
    },
    # --- Soplete ---
    {
        "canonical": "soplete",
        "family": "soplete",
        "aliases": ["soplete", "sopletes", "pistola de calor"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["gas", "soldadura"],
    },
    # --- Sanitaria ---
    {
        "canonical": "teflon",
        "family": "teflon",
        "aliases": ["teflon", "cinta teflon"],
        "misspellings": ["teflón", "teflonn"],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["rosca", "agua"],
    },
    {
        "canonical": "silicona",
        "family": "silicona",
        "aliases": ["silicona", "sellador silicona"],
        "misspellings": ["silicon"],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": ["sanitaria", "neutra", "acetica"],
    },
    {
        "canonical": "cano pvc",
        "family": "cano",
        "aliases": ["cano pvc", "caño pvc", "cano"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"material": "pvc"},
        "context_terms": ["agua"],
    },
    {
        "canonical": "sellador",
        "family": "silicona",
        "aliases": ["sellador", "sellador sanitario"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {"use": "sanitaria"},
        "context_terms": [],
    },
    # --- Otros ---
    {
        "canonical": "rodillo",
        "family": "rodillo",
        "aliases": ["rodillo"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": [],
    },
    {
        "canonical": "guante",
        "family": "guante",
        "aliases": ["guante", "guantes"],
        "misspellings": [],
        "brand_generic": False,
        "maps_dimensions": {},
        "context_terms": [],
    },
]

DEFAULT_FAMILY_RULES = {
    "taladro": {
        "allowed_categories": ["Herramientas Electricas"],
        "match_terms": ["taladro", "percutor"],
        "required_dimensions": [],
        "optional_dimensions": ["brand", "power", "size", "voltage"],
        "dimension_priority": ["power", "voltage", "brand"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["power", "voltage"],
        "presentation_rules": {},
        "substitute_group": "herramienta_electrica",
        "allowed_substitute_groups": ["herramienta_electrica"],
        "blocked_substitute_groups": ["accesorio_perforacion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "amoladora": {
        "allowed_categories": ["Herramientas Electricas"],
        "match_terms": ["amoladora", "angular"],
        "required_dimensions": [],
        "optional_dimensions": ["brand", "power", "size"],
        "dimension_priority": ["power", "size"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["power", "size"],
        "presentation_rules": {},
        "substitute_group": "herramienta_electrica",
        "allowed_substitute_groups": ["herramienta_electrica"],
        "blocked_substitute_groups": ["accesorio_perforacion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "atornillador": {
        "allowed_categories": ["Herramientas Electricas"],
        "match_terms": ["atornillador", "inalambrico"],
        "required_dimensions": [],
        "optional_dimensions": ["brand", "power", "voltage"],
        "dimension_priority": ["voltage", "power", "brand"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["power", "voltage"],
        "presentation_rules": {},
        "substitute_group": "herramienta_electrica",
        "allowed_substitute_groups": ["herramienta_electrica"],
        "blocked_substitute_groups": ["accesorio_perforacion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "herramienta_electrica": {
        "allowed_categories": ["Herramientas Electricas"],
        "match_terms": ["herramienta electrica"],
        "required_dimensions": ["type"],
        "optional_dimensions": ["brand", "power", "voltage"],
        "dimension_priority": ["type", "power", "voltage"],
        "autopick_min_dimensions": ["type"],
        "blocked_autopick_conditions": [{"if_missing": ["type"], "reason": "demasiado_amplio"}],
        "compatibility_axes": ["type", "power", "voltage"],
        "presentation_rules": {},
        "substitute_group": "herramienta_electrica",
        "allowed_substitute_groups": ["herramienta_electrica"],
        "blocked_substitute_groups": ["accesorio_perforacion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "mecha": {
        "allowed_categories": ["Herramientas Electricas", "Herramientas Manuales", "Accesorios"],
        "match_terms": ["mecha", "mecha madera", "mecha metal"],
        "required_dimensions": ["size", "material"],
        "optional_dimensions": ["surface", "use", "length"],
        "dimension_priority": ["material", "size", "surface"],
        "autopick_min_dimensions": ["material", "size"],
        "blocked_autopick_conditions": [
            {"if_missing": ["material"], "reason": "falta_material"},
            {"if_missing": ["size"], "reason": "falta_medida"},
        ],
        "compatibility_axes": ["material", "surface", "size"],
        "presentation_rules": {},
        "substitute_group": "accesorio_perforacion_metal_madera",
        "allowed_substitute_groups": ["accesorio_perforacion_metal_madera"],
        "blocked_substitute_groups": ["accesorio_perforacion_mamposteria"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "broca": {
        "allowed_categories": ["Herramientas Electricas", "Herramientas Manuales", "Accesorios"],
        "match_terms": ["broca", "widia", "hormigon", "ceramica"],
        "required_dimensions": ["size", "material"],
        "optional_dimensions": ["surface", "use", "length"],
        "dimension_priority": ["material", "size", "surface"],
        "autopick_min_dimensions": ["material", "size"],
        "blocked_autopick_conditions": [
            {"if_missing": ["material"], "reason": "falta_superficie"},
            {"if_missing": ["size"], "reason": "falta_medida"},
        ],
        "compatibility_axes": ["material", "surface", "size"],
        "presentation_rules": {},
        "substitute_group": "accesorio_perforacion_mamposteria",
        "allowed_substitute_groups": ["accesorio_perforacion_mamposteria"],
        "blocked_substitute_groups": ["accesorio_perforacion_metal_madera"],
        "brand_generic_terms": ["widia"],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "tornillo": {
        "allowed_categories": ["Bulonería"],
        "match_terms": ["tornillo", "autoperforante", "roscachapa"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "length", "type", "material", "surface", "use", "drive_type", "head_type"],
        "dimension_priority": ["use", "type", "size", "length"],
        "autopick_min_dimensions": ["use"],
        "blocked_autopick_conditions": [
            {"if_missing": ["use"], "reason": "falta_superficie_de_uso"},
        ],
        "compatibility_axes": ["use", "surface", "size", "length", "type", "head_type", "drive_type"],
        "presentation_rules": {"prefer_pack_note": True},
        "substitute_group": "tornilleria_liviana",
        "allowed_substitute_groups": ["tornilleria_liviana"],
        "blocked_substitute_groups": ["fijacion_tarugo"],
        "brand_generic_terms": [],
        "pack_sensitive": True,
        "compatibility_sensitive": True,
    },
    "tarugo": {
        "allowed_categories": ["Fijaciones"],
        "match_terms": ["tarugo", "taco", "fisher", "fischer"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "diameter", "surface", "material", "pack_quantity"],
        "dimension_priority": ["size", "diameter", "surface"],
        "autopick_min_dimensions": ["size"],
        "blocked_autopick_conditions": [{"if_missing": ["size"], "reason": "falta_medida"}],
        "compatibility_axes": ["size", "diameter", "surface", "material"],
        "presentation_rules": {"prefer_pack_note": True},
        "substitute_group": "fijacion_tarugo",
        "allowed_substitute_groups": ["fijacion_tarugo"],
        "blocked_substitute_groups": ["tornilleria_liviana"],
        "brand_generic_terms": ["fisher", "fischer"],
        "pack_sensitive": True,
        "compatibility_sensitive": True,
    },
    "taco": {
        "allowed_categories": ["Fijaciones"],
        "match_terms": ["taco", "fisher", "fischer"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "diameter", "surface", "material", "pack_quantity"],
        "dimension_priority": ["size", "diameter", "surface"],
        "autopick_min_dimensions": ["size"],
        "blocked_autopick_conditions": [{"if_missing": ["size"], "reason": "falta_medida"}],
        "compatibility_axes": ["size", "diameter", "surface", "material"],
        "presentation_rules": {"prefer_pack_note": True},
        "substitute_group": "fijacion_tarugo",
        "allowed_substitute_groups": ["fijacion_tarugo"],
        "blocked_substitute_groups": ["tornilleria_liviana"],
        "brand_generic_terms": ["fisher", "fischer"],
        "pack_sensitive": True,
        "compatibility_sensitive": True,
    },
    "silicona": {
        "allowed_categories": ["Plomeria"],
        "match_terms": ["silicona", "sellador", "sanitaria", "neutra", "acetica"],
        "required_dimensions": [],
        "optional_dimensions": ["use", "type", "presentation", "environment", "color"],
        "dimension_priority": ["use", "type", "presentation"],
        "autopick_min_dimensions": ["use"],
        "blocked_autopick_conditions": [{"if_missing": ["use"], "reason": "falta_uso"}],
        "compatibility_axes": ["use", "type", "environment", "presentation"],
        "presentation_rules": {},
        "substitute_group": "selladores",
        "allowed_substitute_groups": ["selladores"],
        "blocked_substitute_groups": ["plomeria_conduccion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "sellador": {
        "allowed_categories": ["Plomeria"],
        "match_terms": ["sellador", "sellador sanitario"],
        "required_dimensions": [],
        "optional_dimensions": ["use", "type", "presentation", "environment"],
        "dimension_priority": ["use", "presentation"],
        "autopick_min_dimensions": ["use"],
        "blocked_autopick_conditions": [{"if_missing": ["use"], "reason": "falta_uso"}],
        "compatibility_axes": ["use", "type", "environment", "presentation"],
        "presentation_rules": {},
        "substitute_group": "selladores",
        "allowed_substitute_groups": ["selladores"],
        "blocked_substitute_groups": ["plomeria_conduccion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "teflon": {
        "allowed_categories": ["Plomeria"],
        "match_terms": ["teflon", "cinta teflon"],
        "required_dimensions": [],
        "optional_dimensions": ["presentation", "diameter", "length"],
        "dimension_priority": ["presentation", "length"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["presentation", "length", "diameter"],
        "presentation_rules": {},
        "substitute_group": "selladores",
        "allowed_substitute_groups": ["selladores"],
        "blocked_substitute_groups": ["plomeria_conduccion"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "cano": {
        "allowed_categories": ["Plomeria"],
        "match_terms": ["cano", "caño", "pvc", "flexible", "hierro"],
        "required_dimensions": ["material", "diameter"],
        "optional_dimensions": ["use", "pressure_rating", "temperature_rating", "length"],
        "dimension_priority": ["material", "diameter", "use"],
        "autopick_min_dimensions": ["material", "diameter"],
        "blocked_autopick_conditions": [
            {"if_missing": ["material"], "reason": "falta_material"},
            {"if_missing": ["diameter"], "reason": "falta_diametro"},
        ],
        "compatibility_axes": ["material", "diameter", "use", "pressure_rating", "temperature_rating"],
        "presentation_rules": {},
        "substitute_group": "plomeria_conduccion",
        "allowed_substitute_groups": ["plomeria_conduccion"],
        "blocked_substitute_groups": ["selladores"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "conexion": {
        "allowed_categories": ["Plomeria"],
        "match_terms": ["conexion", "codo", "tee", "cupla"],
        "required_dimensions": ["material", "diameter"],
        "optional_dimensions": ["use", "pressure_rating"],
        "dimension_priority": ["material", "diameter"],
        "autopick_min_dimensions": ["material", "diameter"],
        "blocked_autopick_conditions": [
            {"if_missing": ["material"], "reason": "falta_material"},
            {"if_missing": ["diameter"], "reason": "falta_diametro"},
        ],
        "compatibility_axes": ["material", "diameter", "use", "pressure_rating"],
        "presentation_rules": {},
        "substitute_group": "plomeria_conduccion",
        "allowed_substitute_groups": ["plomeria_conduccion"],
        "blocked_substitute_groups": ["selladores"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "pintura": {
        "allowed_categories": ["Pintureria"],
        "match_terms": ["pintura", "latex", "látex", "esmalte"],
        "required_dimensions": ["type", "presentation"],
        "optional_dimensions": ["color", "environment", "use", "finish"],
        "dimension_priority": ["type", "presentation", "environment", "color"],
        "autopick_min_dimensions": ["type", "presentation"],
        "blocked_autopick_conditions": [
            {"if_missing": ["type"], "reason": "falta_tipo"},
            {"if_missing": ["presentation"], "reason": "falta_presentacion"},
        ],
        "compatibility_axes": ["type", "environment", "presentation", "finish", "color"],
        "presentation_rules": {},
        "substitute_group": "pintureria_base",
        "allowed_substitute_groups": ["pintureria_base"],
        "blocked_substitute_groups": ["herramienta_electrica"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "latex": {
        "allowed_categories": ["Pintureria"],
        "match_terms": ["latex", "látex"],
        "required_dimensions": ["presentation"],
        "optional_dimensions": ["environment", "color", "use", "type"],
        "dimension_priority": ["presentation", "environment", "color"],
        "autopick_min_dimensions": ["presentation"],
        "blocked_autopick_conditions": [{"if_missing": ["presentation"], "reason": "falta_presentacion"}],
        "compatibility_axes": ["environment", "presentation", "color"],
        "presentation_rules": {},
        "substitute_group": "pintureria_base",
        "allowed_substitute_groups": ["pintureria_base"],
        "blocked_substitute_groups": ["herramienta_electrica"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "rodillo": {
        "allowed_categories": ["Pintureria"],
        "match_terms": ["rodillo", "antigota"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "type", "surface"],
        "dimension_priority": ["size", "type"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["size", "type", "surface"],
        "presentation_rules": {},
        "substitute_group": "pintureria_accesorio",
        "allowed_substitute_groups": ["pintureria_accesorio"],
        "blocked_substitute_groups": ["pintureria_base"],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "llave": {
        "allowed_categories": ["Herramientas Manuales"],
        "match_terms": ["llave", "francesa", "ajustable"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "type"],
        "dimension_priority": ["type", "size"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["type", "size"],
        "presentation_rules": {},
        "substitute_group": "herramienta_manual",
        "allowed_substitute_groups": ["herramienta_manual"],
        "blocked_substitute_groups": [],
        "brand_generic_terms": ["francesa"],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
    "cable": {
        "allowed_categories": ["Electricidad"],
        "match_terms": ["cable", "obra", "unipolar"],
        "required_dimensions": ["size", "use"],
        "optional_dimensions": ["presentation", "voltage"],
        "dimension_priority": ["size", "use", "presentation"],
        "autopick_min_dimensions": ["size", "use"],
        "blocked_autopick_conditions": [
            {"if_missing": ["size"], "reason": "falta_seccion"},
            {"if_missing": ["use"], "reason": "falta_uso"},
        ],
        "compatibility_axes": ["size", "use", "presentation", "voltage"],
        "presentation_rules": {},
        "substitute_group": "electricidad_conductor",
        "allowed_substitute_groups": ["electricidad_conductor"],
        "blocked_substitute_groups": [],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": True,
    },
    "guante": {
        "allowed_categories": ["Seguridad"],
        "match_terms": ["guante", "guantes"],
        "required_dimensions": [],
        "optional_dimensions": ["size", "material", "use"],
        "dimension_priority": ["size", "use"],
        "autopick_min_dimensions": [],
        "blocked_autopick_conditions": [],
        "compatibility_axes": ["size", "material", "use"],
        "presentation_rules": {},
        "substitute_group": "seguridad_mano",
        "allowed_substitute_groups": ["seguridad_mano"],
        "blocked_substitute_groups": [],
        "brand_generic_terms": [],
        "pack_sensitive": False,
        "compatibility_sensitive": False,
    },
}

DEFAULT_CLARIFICATION_RULES = {
    "tornillo": {
        "prompt": "decime medida o tipo (ej: autoperforante 8x1, hexagonal, etc.)",
        "short_prompt": "¿Es para chapa, madera o durlock?",
        "question_order": ["use", "size", "length", "type"],
        "prompt_by_missing_dimensions": {
            "use": "¿Es para chapa, madera o durlock?",
            "size": "¿Qué medida necesitás?",
            "length": "¿Qué largo necesitás?",
            "type": "¿Autoperforante, cabeza hexagonal u otro tipo?",
        },
        "examples_by_dimension": {
            "use": ["para chapa", "para madera"],
            "size": ["N8", "8mm"],
            "length": ["8x1", "8x1 1/2"],
            "type": ["autoperforante", "hexagonal"],
        },
        "required_dimensions": ["size", "type"],
        "stop_when_dimensions_present": ["use", "size"],
        "blocked_if_missing": ["use"],
        "examples": ["autoperforante 8x1", "hexagonal"],
    },
    "mecha": {
        "prompt": "decime medida y material (ej: mecha para madera 8mm, para metal, etc.)",
        "short_prompt": "¿Para madera, metal, hormigón o cerámica?",
        "question_order": ["material", "size"],
        "prompt_by_missing_dimensions": {
            "material": "¿Para madera, metal, hormigón o cerámica?",
            "size": "¿Qué medida necesitás?",
        },
        "examples_by_dimension": {
            "material": ["madera", "metal"],
            "size": ["8mm", "10mm"],
        },
        "required_dimensions": ["size", "material"],
        "stop_when_dimensions_present": ["material", "size"],
        "blocked_if_missing": ["material", "size"],
        "examples": ["mecha para madera 8mm", "para metal"],
    },
    "broca": {
        "prompt": "decime medida y material",
        "short_prompt": "¿Para hormigón, cerámica o mampostería?",
        "question_order": ["material", "size"],
        "prompt_by_missing_dimensions": {
            "material": "¿Para hormigón, cerámica o mampostería?",
            "size": "¿Qué medida necesitás?",
        },
        "examples_by_dimension": {
            "material": ["hormigón", "cerámica"],
            "size": ["8mm"],
        },
        "required_dimensions": ["size", "material"],
        "stop_when_dimensions_present": ["material", "size"],
        "blocked_if_missing": ["material", "size"],
        "examples": ["broca widia 8mm", "para hormigon"],
    },
    "cano": {
        "prompt": "decime medida y material (ej: PVC 20mm, hierro, flexible, etc.)",
        "short_prompt": "¿PVC, hierro o flexible?",
        "question_order": ["material", "diameter"],
        "prompt_by_missing_dimensions": {
            "material": "¿PVC, hierro o flexible?",
            "diameter": "¿Qué diámetro necesitás?",
        },
        "examples_by_dimension": {
            "material": ["PVC", "hierro"],
            "diameter": ["20mm", "3/4"],
        },
        "required_dimensions": ["material", "diameter"],
        "stop_when_dimensions_present": ["material", "diameter"],
        "blocked_if_missing": ["material", "diameter"],
        "examples": ["PVC 20mm", "hierro"],
    },
    "conexion": {
        "prompt": "decime material y diametro",
        "short_prompt": "¿De qué material y diámetro?",
        "question_order": ["material", "diameter"],
        "prompt_by_missing_dimensions": {
            "material": "¿PVC, hierro o bronce?",
            "diameter": "¿Qué diámetro necesitás?",
        },
        "examples_by_dimension": {
            "material": ["PVC", "hierro"],
            "diameter": ["20mm", "3/4"],
        },
        "required_dimensions": ["material", "diameter"],
        "stop_when_dimensions_present": ["material", "diameter"],
        "blocked_if_missing": ["material", "diameter"],
        "examples": ["codo pvc 20mm"],
    },
    "pintura": {
        "prompt": "decime tipo y cantidad (ej: latex interior blanco 4L, esmalte, etc.)",
        "short_prompt": "¿Látex o esmalte?",
        "question_order": ["type", "presentation", "environment", "color"],
        "prompt_by_missing_dimensions": {
            "type": "¿Látex o esmalte?",
            "presentation": "¿Qué presentación necesitás?",
            "environment": "¿Es para interior o exterior?",
            "color": "¿Qué color buscás?",
        },
        "examples_by_dimension": {
            "type": ["látex", "esmalte"],
            "presentation": ["4L", "20L"],
            "environment": ["interior", "exterior"],
            "color": ["blanco"],
        },
        "required_dimensions": ["type", "presentation"],
        "stop_when_dimensions_present": ["type", "presentation"],
        "blocked_if_missing": ["type", "presentation"],
        "examples": ["latex interior blanco 4L", "esmalte"],
    },
    "latex": {
        "prompt": "decime tipo y litros",
        "short_prompt": "¿Qué presentación necesitás?",
        "question_order": ["presentation", "environment", "color"],
        "prompt_by_missing_dimensions": {
            "presentation": "¿Qué presentación necesitás?",
            "environment": "¿Es para interior o exterior?",
            "color": "¿Qué color buscás?",
        },
        "examples_by_dimension": {
            "presentation": ["4L", "20L"],
            "environment": ["interior", "exterior"],
            "color": ["blanco"],
        },
        "required_dimensions": ["presentation"],
        "stop_when_dimensions_present": ["presentation"],
        "blocked_if_missing": ["presentation"],
        "examples": ["interior 20L"],
    },
    "silicona": {
        "prompt": "decime uso (interior/exterior, neutra/acetica) y presentacion",
        "short_prompt": "¿Es sanitaria, neutra o acética?",
        "question_order": ["use", "type", "presentation"],
        "prompt_by_missing_dimensions": {
            "use": "¿Es sanitaria, de construcción o para vidrio?",
            "type": "¿La necesitás neutra o acética?",
            "presentation": "¿Qué presentación necesitás?",
        },
        "examples_by_dimension": {
            "use": ["sanitaria"],
            "type": ["neutra", "acética"],
            "presentation": ["280ml"],
        },
        "required_dimensions": [],
        "stop_when_dimensions_present": ["use", "presentation"],
        "blocked_if_missing": ["use"],
        "examples": ["neutra 280ml", "sanitaria"],
    },
    "tarugo": {
        "prompt": "decime medida (ej: N6, N8, N10)",
        "short_prompt": "¿Qué medida necesitás?",
        "question_order": ["size", "surface"],
        "prompt_by_missing_dimensions": {
            "size": "¿Qué medida necesitás?",
            "surface": "¿Es para pared maciza, hueca o durlock?",
        },
        "examples_by_dimension": {
            "size": ["N8"],
            "surface": ["pared maciza"],
        },
        "required_dimensions": [],
        "stop_when_dimensions_present": ["size"],
        "blocked_if_missing": ["size"],
        "examples": ["N8"],
    },
    "taco": {
        "prompt": "decime medida",
        "short_prompt": "¿Qué medida necesitás?",
        "question_order": ["size", "surface"],
        "prompt_by_missing_dimensions": {
            "size": "¿Qué medida necesitás?",
            "surface": "¿Es para pared maciza, hueca o durlock?",
        },
        "examples_by_dimension": {
            "size": ["N8"],
            "surface": ["pared maciza"],
        },
        "required_dimensions": [],
        "stop_when_dimensions_present": ["size"],
        "blocked_if_missing": ["size"],
        "examples": ["N8"],
    },
    "rodillo": {
        "prompt": "decime ancho y tipo de pelo",
        "short_prompt": "¿Qué ancho necesitás?",
        "question_order": ["size", "type"],
        "prompt_by_missing_dimensions": {
            "size": "¿Qué ancho necesitás?",
            "type": "¿Antigota o de pelo más largo?",
        },
        "examples_by_dimension": {
            "size": ["22cm"],
            "type": ["antigota"],
        },
        "required_dimensions": [],
        "stop_when_dimensions_present": ["size"],
        "blocked_if_missing": [],
        "examples": ["22cm antigota"],
    },
    "cable": {
        "prompt": "decime seccion, uso y metros aproximados",
        "short_prompt": "¿Qué sección y para qué uso?",
        "question_order": ["size", "use", "presentation"],
        "prompt_by_missing_dimensions": {
            "size": "¿Qué sección necesitás?",
            "use": "¿Es para obra, unipolar u otro uso?",
            "presentation": "¿Cuántos metros aproximados necesitás?",
        },
        "examples_by_dimension": {
            "size": ["2.5mm"],
            "use": ["obra"],
            "presentation": ["20m"],
        },
        "required_dimensions": ["size", "use"],
        "stop_when_dimensions_present": ["size", "use"],
        "blocked_if_missing": ["size", "use"],
        "examples": ["2.5mm obra 20m"],
    },
}

DEFAULT_BLOCKED_TERMS = [
    {
        "term": "herramienta",
        "reason": "demasiado amplio",
        "redirect_prompt": "Decime qué herramienta necesitás o para qué uso es.",
        "family_hint": "herramienta_electrica",
        "block_if_no_dimensions": ["type"],
        "block_if_used_alone": True,
    },
    {
        "term": "tornillo",
        "reason": "familia amplia sin datos de uso",
        "redirect_prompt": "¿Es para chapa, madera o durlock?",
        "family_hint": "tornillo",
        "block_if_no_dimensions": ["use"],
        "block_if_used_alone": True,
    },
]

DEFAULT_COMPLEMENTARY_RULES = {
    "silicona": {
        "targets": ["pistola aplicadora"],
        "max_suggestions": 1,
        "required_source_status": "resolved",
        "required_dimensions": ["presentation"],
        "blocked_when_missing": ["presentation"],
        "compatible_families": ["silicona", "sellador"],
    },
    "pintura": {
        "targets": ["rodillo", "pincel", "bandeja"],
        "max_suggestions": 3,
        "required_source_status": "resolved",
        "required_dimensions": ["presentation"],
        "blocked_when_missing": ["presentation"],
        "compatible_families": ["pintura", "latex"],
    },
    "latex": {
        "targets": ["rodillo", "pincel"],
        "max_suggestions": 2,
        "required_source_status": "resolved",
        "required_dimensions": ["presentation"],
        "blocked_when_missing": ["presentation"],
        "compatible_families": ["pintura", "latex"],
    },
    "taladro": {
        "targets": ["mecha", "broca"],
        "max_suggestions": 2,
        "required_source_status": "resolved",
        "required_dimensions": [],
        "blocked_when_missing": [],
        "compatible_families": ["taladro"],
    },
    "cano": {
        "targets": ["teflon", "sellador"],
        "max_suggestions": 2,
        "required_source_status": "resolved",
        "required_dimensions": ["material", "diameter"],
        "blocked_when_missing": ["material", "diameter"],
        "compatible_families": ["cano", "conexion"],
    },
    "sellador": {
        "targets": ["pistola aplicadora"],
        "max_suggestions": 1,
        "required_source_status": "resolved",
        "required_dimensions": [],
        "blocked_when_missing": [],
        "compatible_families": ["silicona", "sellador"],
    },
}

DEFAULT_SUBSTITUTE_RULES = {
    "rules": [
        {
            "group_id": "accesorio_perforacion_metal_madera",
            "source_families": ["mecha"],
            "allowed_targets": ["mecha"],
            "required_matching_dimensions": ["material", "size"],
            "allowed_dimension_drift": [],
            "blocked_dimension_mismatches": ["material", "surface", "size"],
            "blocked_terms": ["hormigon", "widia"],
            "reason_template": "Mantener mismo material y medida.",
        },
        {
            "group_id": "accesorio_perforacion_mamposteria",
            "source_families": ["broca"],
            "allowed_targets": ["broca"],
            "required_matching_dimensions": ["material", "size"],
            "allowed_dimension_drift": [],
            "blocked_dimension_mismatches": ["material", "surface", "size"],
            "blocked_terms": ["madera", "metal"],
            "reason_template": "Mantener misma superficie y medida.",
        },
        {
            "group_id": "tornilleria_liviana",
            "source_families": ["tornillo"],
            "allowed_targets": ["tornillo"],
            "required_matching_dimensions": ["use"],
            "allowed_dimension_drift": ["size", "length"],
            "blocked_dimension_mismatches": ["use", "surface", "type"],
            "blocked_terms": ["tarugo"],
            "reason_template": "Solo sugerir tornillos del mismo uso.",
        },
        {
            "group_id": "fijacion_tarugo",
            "source_families": ["tarugo", "taco"],
            "allowed_targets": ["tarugo", "taco"],
            "required_matching_dimensions": ["size"],
            "allowed_dimension_drift": [],
            "blocked_dimension_mismatches": ["size", "surface"],
            "blocked_terms": ["tornillo"],
            "reason_template": "Mantener la misma medida de tarugo.",
        },
        {
            "group_id": "selladores",
            "source_families": ["silicona", "sellador", "teflon"],
            "allowed_targets": ["silicona", "sellador", "teflon"],
            "required_matching_dimensions": [],
            "allowed_dimension_drift": ["presentation"],
            "blocked_dimension_mismatches": ["use", "type", "environment"],
            "blocked_terms": ["cano"],
            "reason_template": "No mezclar selladores de distinto uso.",
        },
        {
            "group_id": "pintureria_base",
            "source_families": ["pintura", "latex"],
            "allowed_targets": ["pintura", "latex"],
            "required_matching_dimensions": ["type"],
            "allowed_dimension_drift": ["presentation", "color"],
            "blocked_dimension_mismatches": ["type", "environment"],
            "blocked_terms": ["rodillo"],
            "reason_template": "No cruzar tipos de pintura incompatibles.",
        },
        {
            "group_id": "plomeria_conduccion",
            "source_families": ["cano", "conexion"],
            "allowed_targets": ["cano", "conexion"],
            "required_matching_dimensions": ["material", "diameter"],
            "allowed_dimension_drift": [],
            "blocked_dimension_mismatches": ["material", "diameter", "pressure_rating"],
            "blocked_terms": ["teflon", "sellador"],
            "reason_template": "Mantener material y diámetro compatibles.",
        },
    ]
}

DEFAULT_LANGUAGE_PATTERNS = {
    "misspellings": {
        "teflón": "teflon",
        "silicona": "silicona",
        "fischer": "fisher",
        "látex": "latex",
    },
    "regional_terms": {
        "caño": "cano",
        "broca": "broca",
        "mechas": "mecha",
        "brocas": "broca",
    },
    "brand_generics": {
        "fisher": "taco fisher",
        "fischer": "taco fisher",
        "widia": "broca widia",
    },
    "abbreviations": {
        "obra": "uso obra",
        "sanit": "sanitaria",
        "int": "interior",
        "ext": "exterior",
    },
    "shorthand_dimension_patterns": [
        {"pattern": r"\b(\d+(?:[.,]\d+)?)\s*mm\b", "replacement": r"\1mm"},
        {"pattern": r"\b(\d+)\s*x\s*(\d+)\b", "replacement": r"\1x\2"},
        {"pattern": r"\b(\d+)\s*l\b", "replacement": r"\1l"},
        {"pattern": r"\b(\d+)\s*ml\b", "replacement": r"\1ml"},
    ],
    "surface_aliases": {
        "durlock": "durlock",
        "chapa": "chapa",
        "madera": "madera",
        "metal": "metal",
        "hormigon": "hormigon",
        "ceramica": "ceramica",
    },
}

DEFAULT_ACCEPTANCE_PATTERNS = {
    "accept_phrases": [
        "dale", "dale cerralo", "lo quiero", "acepto", "acepto el presupuesto",
        "avancemos", "confirmalo", "confirma", "me sirve", "listo cerralo",
        "cerralo", "confirmame", "te confirmo", "me lo quedo", "si confirmo",
        "lo acepto", "esta bien acepto", "ok acepto", "vamos",
        "si dale", "perfecto dale", "de acuerdo", "adelante",
    ],
    "reset_phrases": [
        "nuevo presupuesto", "empecemos de nuevo", "empezar de nuevo",
        "borrar presupuesto", "limpiar presupuesto", "cancelar presupuesto",
        "reset", "nueva cotizacion", "empezar otra vez", "olvidate",
        "borra eso", "arranquemos otra vez", "empezamos de nuevo",
    ],
    "merge_phrases": [
        "sumalo", "mezclalo", "sumame", "juntalo", "junto", "merge", "igual",
        "dale suma", "agregalo", "al mismo", "segui con este", "seguí con este",
        "este mismo", "sigo con este", "al actual", "suma", "sumalo al actual",
    ],
    "new_quote_phrases": [
        "nuevo", "de cero", "borralo", "nuevo presupuesto", "arranca",
        "arranquemos", "empezar de nuevo", "empezamos de nuevo",
        "no quiero el anterior", "otro", "otro presupuesto", "empezá de cero",
        "cero", "limpio",
    ],
}

DEFAULT_FAQ_FALLBACK_PATH = "faqs.json"

ALLOWED_DIMENSIONS = {
    "material", "size", "diameter", "use", "presentation", "brand", "type",
    "color", "power", "voltage", "length", "surface", "environment", "thread",
    "head_type", "drive_type", "pressure_rating", "temperature_rating",
    "pack_quantity", "unit_mode", "finish",
}
DEFAULT_ITEM_FAMILY_MAP = {
    "taladro":          {"Herramientas Electricas"},
    "amoladora":        {"Herramientas Electricas"},
    "atornillador":     {"Herramientas Electricas"},
    "mecha":            {"Herramientas Electricas", "Herramientas Manuales", "Accesorios"},
    "broca":            {"Herramientas Electricas", "Herramientas Manuales", "Accesorios"},
    "martillo":         {"Herramientas Manuales"},
    "destornillador":   {"Herramientas Manuales"},
    "llave":            {"Herramientas Manuales"},
    "tornillo":         {"Tornilleria"},
    "autoperforante":   {"Tornilleria"},
    "buloneria":        {"Tornilleria", "Fijaciones"},
    "tarugo":           {"Fijaciones"},
    "taco":             {"Fijaciones"},
    "fijacion":         {"Fijaciones"},
    "pintura":          {"Pintureria"},
    "latex":            {"Pintureria"},
    "esmalte":          {"Pintureria"},
    "rodillo":          {"Pintureria"},
    "pincel":           {"Pintureria"},
    "brocha":           {"Pintureria"},
    "bandeja":          {"Pintureria"},
    "silicona":         {"Plomeria"},
    "sellador":         {"Plomeria"},
    "teflon":           {"Plomeria"},
    "cano":             {"Plomeria"},
    "caño":             {"Plomeria"},
    "conexion":         {"Plomeria"},
    "guante":           {"Seguridad"},
    "casco":            {"Seguridad"},
    "lente":            {"Seguridad"},
    "cable":            {"Electricidad"},
    "interruptor":      {"Electricidad"},
    "toma":             {"Electricidad"},
}

DEFAULT_CATEGORY_ALIASES = {
    "taladro":          "Herramientas Electricas",
    "amoladora":        "Herramientas Electricas",
    "atornillador":     "Herramientas Electricas",
    "martillo":         "Herramientas Manuales",
    "destornillador":   "Herramientas Manuales",
    "llave":            "Herramientas Manuales",
    "tornillo":         "Tornilleria",
    "autoperforante":   "Tornilleria",
    "tarugo":           "Fijaciones",
    "taco":             "Fijaciones",
    "fijacion":         "Fijaciones",
    "pintura":          "Pintureria",
    "latex":            "Pintureria",
    "esmalte":          "Pintureria",
    "rodillo":          "Pintureria",
    "pincel":           "Pintureria",
    "brocha":           "Pintureria",
    "silicona":         "Plomeria",
    "sellador":         "Plomeria",
    "teflon":           "Plomeria",
    "cano":             "Plomeria",
    "conexion":         "Plomeria",
    "guante":           "Seguridad",
    "mecha":            "Herramientas Electricas",
    "broca":            "Herramientas Electricas",
    "cable":            "Electricidad",
}
